import { renderJointOptions, renderLandmarkGuide } from './rom-joints.js';

export function renderAnkleCapture() {
  return `<section class="ankle-intro"><div><span>외출 전 · 앉아서 준비</span><h1>내 발목 기준 만들기</h1><p>신발을 신고, 한 발씩 편안하게 움직여요.</p></div><button type="button" data-view="live">현재 상태 보기 →</button></section>
  <div class="ankle-side-picker" role="group" aria-label="측정할 발 선택"><button type="button" data-rom-action="ankle-left" aria-pressed="true"><span>01</span><b>왼발</b><small data-ankle-side-state="left">기록 전</small></button><button type="button" data-rom-action="ankle-right" aria-pressed="false"><span>02</span><b>오른발</b><small data-ankle-side-state="right">기록 전</small></button></div>
  <div class="rom-layout motion-capture ankle-capture">
    <section class="rom-camera-panel" aria-label="발목 카메라"><div class="rom-panel-head"><h2>발목 카메라</h2><span data-rom-camera-status>카메라 대기</span></div>
      <div class="rom-video-stage" data-rom-stage><video data-rom-video autoplay muted playsinline aria-label="발목 웹캠 영상"></video><canvas data-rom-overlay aria-label="발목 계산에 쓰는 네 점"></canvas><div class="rom-video-empty" data-rom-empty><div data-ankle-empty-guide>${renderLandmarkGuide('left_ankle')}</div><b>이렇게 옆에서 촬영해요</b><p>무릎 · 발목 · 뒤꿈치 · 발끝</p></div><span class="rom-video-label" data-rom-view-label>왼발 옆면 · 본인 기준</span></div>
      <label class="rom-consent"><input type="checkbox" data-rom-consent> 카메라 사용 동의 · 영상 저장 안 함</label>
      <div class="rom-camera-tools"><button type="button" class="rom-primary" data-rom-action="start">카메라 켜기</button><button type="button" data-rom-action="stop" disabled>끄기</button><label><input type="checkbox" data-rom-mirror> 거울 보기</label><span data-rom-fps hidden></span></div>
      <details class="ankle-camera-options"><summary>다른 카메라 선택</summary><label class="rom-camera-select">사용할 카메라<select data-rom-camera-select aria-describedby="rom-camera-help"><option value="">기본 카메라</option></select></label><p id="rom-camera-help" data-rom-camera-help>카메라를 켜면 연결된 장치가 표시돼요.</p></details>
      <p class="rom-quality" data-rom-quality role="status">카메라를 켜 주세요.</p>
    </section>
    <section class="rom-setup-panel ankle-steps" aria-label="발목 준비 순서">
      <section class="ankle-step" data-rom-step="camera"><div class="ankle-step-title"><span class="step-number">1</span><h2>옆면을 보여 주세요</h2><small data-rom-step-state>대기</small></div><p data-ankle-framing>왼발의 무릎부터 발끝까지 보여 주세요.</p><label class="rom-check"><input type="checkbox" data-rom-direction-confirmed> 선택한 발의 옆면 · 화면에는 나만</label><p class="ankle-scope-note">인식이 안 되면 카메라를 조금 멀리 두세요.</p>
        <div hidden><select data-rom-config="metric">${renderJointOptions()}</select><select data-rom-config="posture"><option value="seated">앉아서</option></select><input type="radio" name="rom-view" value="front"><input type="radio" name="rom-view" value="left" checked><input type="radio" name="rom-view" value="right"><p data-rom-guide></p><div data-rom-landmark-guide></div></div>
      </section>
      <section class="ankle-step" data-rom-step="pose"><div class="ankle-step-title"><span class="step-number">2</span><h2>3초 가만히 있어요</h2><small data-rom-step-state>대기</small></div><p>앉아서 발을 편히 놓고 센서 기준을 맞춰요.</p><button type="button" data-rom-action="ankle-neutral" class="ankle-neutral-button">센서 기준 맞추기</button><p data-ankle-calibration role="status">카메라 인식과 신발 연결이 필요해요.</p><button type="button" class="ankle-camera-only" data-rom-action="ankle-camera-only" aria-pressed="false">센서 없이 카메라만 기록</button><button type="button" class="ankle-connection-link" data-view="devices">신발 연결 확인 →</button></section>
      <section class="ankle-step" data-rom-step="record"><div class="ankle-step-title"><span class="step-number">3</span><h2>15초 움직여요</h2><small data-rom-step-state>대기</small></div><p>발끝을 천천히 위아래로, 양끝에서 잠깐 멈춰요.</p><div class="rom-record-box"><div><b data-rom-record-title>편안한 범위만 기록</b><span data-rom-progress-text>0 / 15초</span></div><progress data-rom-progress max="15" value="0" aria-label="기록 진행률"></progress><p id="rom-record-help" data-rom-record-help role="status">카메라를 켜 주세요.</p><div class="rom-buttons"><button type="button" class="rom-primary" data-rom-action="record" aria-describedby="rom-record-help" disabled>15초 기록 시작</button><button type="button" class="rom-danger" data-rom-action="abort" disabled>중단</button></div><small>아프거나 불편하면 바로 멈추세요.</small></div></section>
    </section>
  </div><section class="ankle-today"><div class="ankle-section-title"><div><span>오늘 기록한 두 발</span><h2>나의 기준과 현재 상태</h2></div></div><div data-ankle-status></div><p class="ankle-scope-note">카메라는 발목 각도, 센서는 발 자체의 기울기를 기록해요. 걷는 중에는 비교를 기다립니다.</p><details class="ankle-method"><summary>비교 방법 · 저장 범위</summary><p>센서 기준 자세의 중력 방향을 0°로 맞춘 뒤, 카메라가 유효하게 인식된 때 함께 받은 BMI270 기울기를 기록합니다. 서로 다른 각도를 빼거나 같은 값으로 보정하지 않습니다. 두 장치는 정밀 시간 동기화되어 있지 않습니다.</p><p>저장된 기울기의 95백분위에 표시 여유 5°를 더한 값을 1초 이상 벗어나면 화면에 확인 안내를 표시합니다. 걸을 때나 데이터가 끊기면 비교하지 않습니다. 이는 부상 위험 판정이나 의료적 안전 한계가 아닙니다.</p><p>각도 기록은 PC에, 오늘 센서 기준은 이 브라우저 탭에 저장됩니다. 다른 휴대폰·탭에는 자동 전달되지 않습니다. 날짜·기기 전원이 바뀌거나 다시 착용하면 기준을 다시 기록하세요. 폰에서 연속 배경 감시를 보장하지 않습니다.</p></details></section>`;
}
